@startuml lanchonete
abstract Class Pessoa{
    #nome: String
    #cpf: String
}
Class Pedido{
    -numeroPedido: int
    -nomeAtendente: String
}
Class Avaliacao{
    -Pedido: pedido
    -String: avaliacao
}

Interface CRUD{
    void cadastrar()
    void visualizar()
    void atualizar()
    void remover()
}

Class Produto{
    -codigo: int
    -valor: double
    -quantiade: int
    -nome: String
}

Class Item{
    -codigo: int
    -ListaProduto: ArrayList
}

Class Estoque{

}


Class Cliente{

}

Class Atendente{
    -metaDiaria: int
}

Class CadastroCliente{
    -ListaClientes: ArrayList
}

Class CadastroPedido{
    -ListaPedidos: ArrayList
}

Class CadastroAtendente{
    -ListaAtendentes: ArrayList
}

Class CadastroEstoque{
    -ListaItem: ArrayList
}

Class CadastroAvaliacao{
    -ListaAvaliacao: ArrayList
}

Pessoa <|-- Cliente: é
Pessoa <|-- Atendente: é
CRUD <|-- CadastroCliente: implementa
CRUD <|-- CadastroAtendente: implementa
CRUD <|-- CadastroEstoque: implementa
CRUD <|-- CadastroPedido: implementa
Cliente *-- "1" Pedido: contém
Item "1" *-- "muitos" Produto : contém
Atendente *-- "1" Pedido: contém
Pedido *-- "1" Avaliação: contém
CadastroPedido -- Cliente
CadastroPedido -- Atendente
CadastroPedido -- Pedido
CadastroPedido -- Estoque
CadastroCliente -- Cliente
CadastroAtendente -- Atendente
CadastroEstoque -- Item
CadastroAvaliacao -- Avaliacao
CadastroAvaliacao -- CadastroPedido
@enduml